### PR TITLE
engine update, backstep, history, new graphs

### PR DESCRIPTION
**Pull request by mrwasp**
List of changes:
- storing vars and orders in arrayList
- numbering of addresses from 14/15 register
- added history and backstep function
- new graphics of buttons

### CODE REVIEW

**Comment by Tomivix** [comment]
Love the new buttons @mrwasp, you did really well. As for the code I will check it in the evening as I'm going shopping right now. Still surprised you managed to do so much work in just a single day.

**Comment by Tomivix** [comment]
Well, when I said 'in the evening' I didn't necessarily meant evening of the same day, right? Anyways here is your feedback @mrwasp. It's just a few details honestly but it would be nice if you could fix those:
- Change order of the buttons on the right from *Run/Pause -> Step Forward -> Step Back* to *Step Back -> Run/Pause -> Step Forward* please. It would look better this way in my opinion.
- When you back-step it changes values alright but the problem is with the arrow. I think it should at least point the other way around just like the data flows backwards (more like a suggestion for @Aicedosh) 

Well I was supposed to add something more here but I can't find any other mistakes to be honest. I'm not sure if it's a good idea to make an all-in-one execute() function but since it works okay I think we can have that for now. That would be all -  just change the order of the buttons and I will have no more complaints.

**Comment by Tomivix** [comment]
Just a heads-up for @mrwasp since I don't know if GitHub alerts mentioned users about updated comments. By the way I want to hear your opinion on this one before merging pull request too, @Aicedosh.

**Comment by Aicedosh** [comment]
Since (as I mentioned) my update branch already contains those commits, I'd suggest you pulled my branch instead. I'll make a final commit and pull request in a moment after I change order of those buttons.

**Comment by Tomivix** [comment]
Sounds good. Then this one gets closed and we're moving all discussion about @mrwasp's commit to #29.

**Pull request closed without merging**
