### PR TITLE
Build, step, run functions

### PR DESCRIPTION
**Pull request by mrwasp**
It began to work, I tested our 'quadratic equation' and processing it's ok, but there are some problems with GUI - registers and memory cells aren't always refreshed. And orders aren't written to memory cells.

### CODE REVIEW

**Comment by Tomivix** [comment]
Just one general tip before I go to sleep @mrwasp : make use of the **Parser.getPos** method. It was designed especially for extracting particular parts of the line string, so there's no need to implement this again. As for your code I'll review it tomorrow. Since you modify GUI classes I'd like to hear @Aicedosh opinion as well.

**Comment by mrwasp** [comment]
@Tomivix Thanks, I'll check it out for a while and update.
@Aicedosh GUI classes was edited because this parts did not work well - I think you'll see why

**Comment by Aicedosh** [comment]
Yes I can understand why. There's huge mess with memory cell indexes so I think we should separate the names for "indexes" and "addresses". I'll be able to take a look at it in about an hour or so and I'll post the updated version

**Comment by Tomivix** [comment]
Okay, then everything is okay, I'm looking forward to updates from both of you. I'll probably commit to mrwasp/hpa/wasp before merging to clean the code a bit @mrwasp , as it's a bit dirty right now.

**Comment by Aicedosh** [comment]
"a bit" ;)

**Comment by mrwasp** [comment]
I added new version - functions use Parser.getPos, and now RM commands work for arguments "offset(reg)"

**Comment by Aicedosh** [comment]
And I'm nearly done fixing Engine/View communication. Not sure where to commit those changes though

**Comment by Tomivix** [comment]
You can use your Aicedosh/hpa/ViewDev since you already have an open pull request on it @Aicedosh . If you worry about possible conflicts you can commit to mrwasp/hpa/wasp. I'll review both your updates later.

Anyways I'll push updated syntax splitting/highlighting methods at some point today. Seems like I'll stick with word boundary regexes (something like "(?<!^)\\b") but those are a bit tricky so I need a bit more time.

**Comment by Tomivix** [comment]
I don't see any obvious bugs so it should do for now. Doesn't change the fact that code is 'a bit' dirty and I already see room for a few optimizations (like this bulk jump function). Good job @mrwasp  but before I proceed I want explanation about those overlaping commits here and in #20. Once we solve it I'll merge.

**Pull request merged**
