### PR TITLE
New update with fixed offset and separated methods

### PR DESCRIPTION
**Pull request by Tomivix**
Fixed wrong offset on empty lines, renamed main package from 'pseudo' to 'core' and moved all syntax splitting methods from 'Engine' to newly created class 'Parser' (also making them static for ease of use).

### CODE REVIEW

**Comment by Tomivix** [comment]
Well, I thought it was pretty obvious but I'm waiting for your opinions @Aicedosh and @mrwasp. You know, I'm committing to 'update' instead of 'master' and starting an issue here for a reason...

**Comment by Aicedosh** [comment]
Looks good for me

**Comment by mrwasp** [comment]
For me too

**Comment by Tomivix** [comment]
Since there seems to be no complaints I'll merge this pull request now.

**Pull request merged**
