### PR TITLE
Adding option to save and read from file

### PR DESCRIPTION
**Pull request by Tomivix**
This is a pretty dirty version of file saving/reading. Doesn't have any real means of validating the selected file but it should do the trick for now. I will improve it later today but that's all I can offer before KNI meeting.

### CODE REVIEW

**Comment by Tomivix** [comment]
Waiting for your opinions @Aicedosh and @mrwasp. I still should be able to make some small changes before the meeting if you see any problems. Also does anyone have a notebook which isn't as crappy as mine and has Java RE installed? Relying on organizers for that part usually isn't the best idea...

**Comment by mrwasp** [comment]
One bug found: in save you have "\<\<\<SEPARATOR\>\>" but in load "\<\<\<SEPARATOR\>\>\>", which causes that we aren't able to load previously saved file. All the rest works enough good by now.

**Comment by Tomivix** [comment]
Yeah, right... I was using older .hpa file for testing and it had correct separator. Seems like I accidentally deleted one character in the meantime. Thanks for that @mrwasp, will change that right now.

**Comment by Tomivix** [comment]
Okay, fixed it @mrwasp. I will wait a little more in case @Aicedosh shows up. Also do you have serviceable laptop just in case something goes wrong? Mine isn't fit for anything besides browsing web unfortunately...

**Comment by Aicedosh** [comment]
I was just going to report the same bug :) Anyways I have a laptop that might work but it'd be better if someone else took his as well.

**Comment by Tomivix** [comment]
Okay, then I think I can merge this one safely. Sorry for it being so rough but I'm too sleepy to come up with something better, Please bring your laptop if you can, @Aicedosh. Maybe @mrwasp has one as well?

**Comment by Tomivix** [comment]
Okay, done. Now I will make .jar file, add it to the project and mark current status as the v0.9.9 release.

**Comment by mrwasp** [comment]
Yes, I'll take my laptop too.

**Comment by Tomivix** [comment]
Good. Wait a while and I will add this .jar so that you can test if it works for you guys as well.

**Comment by Aicedosh** [comment]
I'm afraid that I won't be able to. I have to go in ~5 mins

**Comment by Tomivix** [comment]
It's here.

**Comment by mrwasp** [comment]
Ok, works for me, then I go!

**Pull request merged**
