### PR TITLE
(Yet another) GUI updates

### PR DESCRIPTION
**Pull request by Aicedosh**
-Added address label to memory cells with labels (temporary solution)
-Using images made by @mrwasp (slightly modified) as buttons
-Scaling window size if necessary (for smaller displays)

### CODE REVIEW

**Comment by mrwasp** [comment]
Looks good, but why hovered is red?

**Comment by Aicedosh** [comment]
Colors and overall look of buttons are up to you @mrwasp. I simply desatureted disabled one and used the old graphics for hovered over.

**Comment by Tomivix** [comment]
Looks good to me but what's up with the colors @Aicedosh ? Aren't we gonna use the red-styled images for anything? I thought we will have grayed-out-style for inactive, red-styled for acticve and green-styled for hovered (or the other way around) or am I missing something here?

**Comment by Aicedosh** [comment]
Together with @mrwasp we changed the concept so that the buttons look more reasonable. I honestly don't see why we'd use red image as hovered over (Also are you testing the version from today?)

**Comment by Tomivix** [comment]
I've checked both versions (from yesterday and from today). Well if it's as you say and you're both okay with how things are now (looking at the conversation flow I wasn't sure about @mrwasp opinion) then I guess that puts me in minority. Anyways good job @Aicedosh  and I'm going to merge it in a while.

**Comment by mrwasp** [comment]
I think brighter green is better than red, red associated with 'something wrong'.

**Pull request merged**
