### PR TITLE
The long awaited update from @Tomivix

### PR DESCRIPTION
**Pull request by Tomivix**
Looks like the update finally is here. Just as I said it contains cleaned up code along with the new less strict syntax parsing and highlighting functions. Also removed parts of the code which I deemed obsolete. Wating for your opinion on this one @Aicedosh and @mrwasp . I hope you still take a look here from time to time.

### CODE REVIEW

**Comment by mrwasp** [comment]
Finally! Nice to see this project is still alive :D I really like this update since now I can use as many whitespaces as I want.

**Comment by Tomivix** [comment]
Well, as long as makes you happy... Many whitespaces... Anyways, thanks for the feedback, now I'll just wait for @Aicedosh opinion like always. Also take a look at #25, apparently @Asiek777 made something for us...

**Comment by Aicedosh** [comment]
Looks fine for me

**Comment by Tomivix** [comment]
Well, since both of you seem to be happy with the update I'm gonna merge it now. I should probably wait for @Asiek777's opinion as well but I don't think he will deliver anytime soon so whatever.

**Pull request merged**
