### PR TITLE
Fixed the issues addresed by @Tomivix

### PR DESCRIPTION
**Pull request by Aicedosh**

### CODE REVIEW

**Comment by Tomivix** [comment]
Good job @Aicedosh ! 
Input restrictions seem to work A-okay so it no longer throws any errors or breaks format conversion. Box of the 15th register also fits inside the window, but in my case now the window is a bit too tall. Is it possible to make window height dynamic (set it based on user's device screen height)? 

Also the last fix I asked for doesn't seem to work - auto selection works only when editor opens, not when I manually change the field by clicking with my mouse. _(Please remove that annoying 'Focusing' line...)_

Will wait a while for your response before merging. Also take a look at the project if you haven't already.

**Comment by Aicedosh** [comment]
Glad you like it.
-What do you mean by "setting it based on user's device screen height"? You mean stretching the window to fill the screen, streching it with register cells or calculating the optimal window size on the fly based on the inside components?
-I missed that part. Anyways doesn't double clicking on JTextField auto select all text (I can't test it now cause I'm not at my PC)

I looked at the project and it seems that I can't edit it (not that I would want to)

**Comment by Tomivix** [comment]
- What I mean is that window can have some predefined height but if it's more than screen height it should be reduced to that value. Right now, when I open the GUI, everything below 14th register box is overlayed by start bar. Since there's no resize option it's a bit problematic in my opinion.
- Yeah you're right about the second one. Double click does indeed select all content in JTextField. I just thought it would be easier if it was done automatically but you can skip that part if you want.

Once again I'm postponing merge so that you can post your response @Aicedosh . Too bad you can't edit the project, that means I have to open separate issue just for handing out open tasks...

**Comment by Aicedosh** [comment]
I'll take a look at the window size stuff probably later today. I think I'll skip the auto-select-on-focus-thingie, not that it's hard to implement, but I believe I'd get hard to e.g. add a single digit to the end

**Comment by Tomivix** [comment]
Okay, then I have no more questions. I'll merge your pull request now and update the project.

**Pull request merged**
