### PR TITLE
Icon

### PR DESCRIPTION
**Pull request by mrwasp**
I think icon should look in style like this, maybe in the other colors.

### CODE REVIEW

**Comment by Tomivix** [comment]
Thank you for your hard work @mrwasp! I have no complaints about the help icon but I'd like to see a few more variations of the logo, if you don't mind. Until then I'm going to wait with the merging of this request.

**Comment by mrwasp** [comment]
I finally added some versions of icon, for me 2 or 5 looks enough good, any suggestions?

**Comment by Tomivix** [comment]
I agree the second one looks pretty good but I don't like the fifth that much honestly. Anyways, why not try something simplified and more suggestive, @mrwasp? I appreciate the tiny HPA source code extracts you put into your icons but you forget one thing: this icon will always be presented in small size. Those extract won't be readable unless someone zooms in the icon deliberately, which probably won't happen often. I suggest you either remove them or make them more recognizable somehow, like using bigger font etc.

**Comment by mrwasp** [comment]
What about something like that? (new concept!)

**Comment by Tomivix** [comment]
It's not the most important concept but I like it nevertheless. Just a few finishing touches I'd like to see:
- How about using a little vivider colors? Wouldn't it match other graphics from the GUI better this way?
- I like usage of perspective but it appears rightmost edge of the cube is crooked. Can you fix this part?
- Reduce the size of the icon. We don't need such resolution or empty space around the actual icon. 
- Maybe emphasize the edges of the cube with some darker line? (not sure about this one though)

Also I forgot about to tell you about [this one](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485(v=vs.85).aspx) @mrwasp. This guidelines might come in handy in future.

**Pull request closed without merging**
