### PR TITLE
View updates

### PR DESCRIPTION
**Pull request by Aicedosh**
-Reworked arrow pointing to memory
-Added labels to code panels
-Reorganized packages

### CODE REVIEW

**Comment by Tomivix** [comment]
All updates seem okay, but do we really need to separate it into so many subpackages?

**Comment by Aicedosh** [comment]
It helps to not get lost. I generally create new subpackage if I have more than 2 related files

**Comment by Tomivix** [comment]
OK cool. Will merge for now, I just meant try not to create subpackages with too many levels. Three levels like view.code.documents are okay but make it any more and browsing becomes needlessly complicated.

**Comment by Aicedosh** [comment]
Okay, I'll try

**Pull request merged**
