### PR TITLE
Create License

### PR DESCRIPTION
**Pull request by Asiek777**
This is 3-Clausule BSD License for our program

### CODE REVIEW

**Comment by Tomivix** [comment]
My counter-proposition would be [this one](https://creativecommons.org/licenses/by-nc-sa/3.0/).

Also one important thing @Asiek777 : I noticed it only now but you've made pull request only on the license commit.  Please add the credits commit (namely b1aff93) as well and then we will discuss it together.

**Comment by Tomivix** [comment]
Still holding my counter-proposition. Maybe @Aicedosh and @mrwasp will state their opinions as well?

**Comment by mrwasp** [comment]
It's ok for me

**Comment by Tomivix** [comment]
Which of them is ok for you @mrwasp: mine or @Asiek777's one? It looks like you're not even trying...

**Comment by Aicedosh** [comment]
Do we really care about commercial use of our program? Is it the only difference between those two licenses or am I missing something?

**Comment by Tomivix** [comment]
Well @Aicedosh, not going into the details there are two major differences. One of them is prohibition of commercial usage (as you noticed) and the second one is copyleft/share-alike part (users must redistribute licensed work under the same license). I personally don't want anyone to make any profit of our program.

Also I repeat my question @mrwasp: which one of the licenses is ok for you, mine or @Asiek777's one?

**Comment by mrwasp** [comment]
Ok, I looked at this one more time and @Tomivix's version sounds better - for reason which you mentioned (commercial usage)

**Comment by Tomivix** [comment]
Okay, thanks for the input @mrwasp. Now I'm just waiting for @Aicedosh's final decision and I think we'll incorporate one of those licenses into our project. 

(*I know we should wait for @Asiek777 but he probably won't show anytime soon so I no longer care...*)

**Comment by Aicedosh** [comment]
The CC one sounds better for me as well

**Comment by Tomivix** [comment]
Well, if you both like my proposition better then I'm closing this issue and will add the chosen license manually. Hopefully @Asiek777 won't mind and will show up once again sometime in the future...

**Comment by Asiek777** [comment]
Ok, if you think, that somebody will ever do something usefull with our code...

**Comment by Tomivix** [comment]
I'm not completely sure about that @Asiek777 but just as they say 'better safe than sorry'. We can always change it in the future if this causes some problems but for the time being we're going to play it safe...

**Pull request closed without merging**
