### PR TITLE
Wasp did something

### PR DESCRIPTION
**Pull request by mrwasp**
I finally look at code and:
1) I don't know why but text in directives/orders is always red for me
2) Dir/Order StyledDocument can't be merge to one class? The only difference I saw is CYAN/BLUE as command color.
3) I propose optimization for storing text indexes - ArrayList<TextObject> rather than int[4][]
And I really need to get better in using Git...

### CODE REVIEW

**Comment by Tomivix** [comment]
~~Good to see you back @mrwasp !  And good to see you write some new code as well! I'd like to take a look at it ASAP but unfortunately I'm too sleepy for that now... I'll give you some feedback on it as soon as I get back home tomorrow.~~

**Comment by Tomivix** [comment]
Okay now for your feedback @mrwasp :
- f189e00 - It seems you don't know what submodules are for. Submoduling your own repository does absolutely nothing aside from wasting space. **Therefore this commit is rejected.**
- 698d57a, 6e086d6, 1f73b97, 93b77f9 - Thanks for presenting your own version but there are two major problems with it. ~~One, the syntax coloring seems to be broken according to you, which is unacceptable (breaking stuff that already works is not cool). Fix that and we can talk.~~ Well, it looks like you resolved this mystery, so it's okay now. Second, creating separate object for each word doesn't seem like an 'real optimization' for me. I'll wait for @Aicedosh opinion on that before final decision though.

Pull request **rejected** for now. Will keep it open in case you deliver. (_Also it already has conflicts..._)

**Comment by Aicedosh** [comment]
I don;t think there's much of a optimization either. I'd say no to those changes as well

**Comment by Tomivix** [comment]
As @Aicedosh also seems opposed to your optimizations I think the final result is obvious. Pull request is **rejected** and since you didn't deliver any fixes @mrwasp I'm taking the liberty of closing this case.

**Pull request closed without merging**
