### PR TITLE
Update test

### PR DESCRIPTION
**Pull request by Aicedosh**
* While the cursor is hovering over a disabled button it changes to regular pointer instead of the hand
	* Editing of Registers / Memory cells is disabled while the code is executed to avoid any possible bugs
	* Currently edited / executed line of the code is being highlighted (fixed last line coloring)
	* All semi-colons are replaced with colons
	* All but run buttons are disabled during code run
	* Buttons have been slightly reorganized

(Also including all of @mrwasp 's updates)

### CODE REVIEW

**Comment by Tomivix** [comment]
I'm sure @mrwasp is okay with his own commit being in someone else's pull request, right? Since your update deals only with the GUI class files I think he won't have problems with this one either. Therefore I assume it's safe to merge it without any further discussion. Correct me if I'm wrong @Aicedosh.

**Comment by Aicedosh** [comment]
Seems legit

**Comment by Tomivix** [comment]
Nice one. Then I will merge it right now.

*UPDATE : @mrwasp also likes the idea so there should be no complaints*

**Comment by mrwasp** [comment]
Yes, it's not problem for me, I just  checked this update - looks and works good for me.

**Comment by Tomivix** [comment]
One more thing @Aicedosh and @mrwasp. As for my update it seems like I will pull tomorrow after getting back home. Opening/saving files will be ready and maybe I will manage to add some more small fixes but that would be all. Highlighting of invalid parts of the code won't be ready anytime soon unfortunately...

**Comment by Aicedosh** [comment]
Sounds good enough. Are we planning to create a first release then, before tomorrow 6PM?

**Comment by Tomivix** [comment]
Yes we do plan to make a .jar file. It may be incomplete but since everything is working there shouldn't be any problems. We'll just name it 0.9.9 or something along these lines. It will look better if we present an actual release instead of compile-it-yourself source code during the KNI meeting, right?

**Comment by mrwasp** [comment]
Sounds good, maybe we will finally know who is our 'mentor'

**Comment by Tomivix** [comment]
Yeah, maybe we will finally be able to meet her after 2 months. Hopefully they will allow us to present our program during the meeting. Since we have no way of contacting them I'm not entirely sure it will work out...

**Pull request merged**
