### PR TITLE
Create Credits

### PR DESCRIPTION
**Pull request by Asiek777**

### CODE REVIEW

**Comment by Tomivix** [comment]
It's pretty short and not too amazing but I guess it works anyways. I'm fine with adding it to our project but like always will wait for @Aicedosh and @mrwasp opinion before doing anything. *(maybe they will deliver)*

**Comment by mrwasp** [comment]
It's ok for me

**Comment by Aicedosh** [comment]
Same for me, I don't know what else could be in there.
BTW it looks like the IDA pricing is "only" 1019 EUR (I think I gotta get stronger glasses)

**Comment by Tomivix** [comment]
Okay, will merge this one in a while. As for the IDA the main problem is not the price (250 EUR per person isn't that big of a deal) but availability, As far as I know they sell it only to "selected and trusted" customers...

**Pull request merged**
